### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by brianamarie** [githubteacher/experimental-gitter-repo#1]
I wonder if this will appear in Gitter

**Comment by hcanna** [comment]
@brianamarie ... how did you link this repo to our gitter chat?

**Comment by brianamarie** [comment]
@hcanna It did it automatically ✨ with the magic of Gitter ✨

**Comment by brianamarie** [comment]
OH link the repo - I totally misunderstood. I went to gitter.im and did it through that interface.
